trythat

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -665,12 +665,22 @@ jobs:
             test_tool python \"Python\" || FAILED=1
             test_tool go \"Go\" version || FAILED=1
             test_tool wasm-opt \"Binaryen\" || FAILED=1
+            test_tool ssh \"ssh\" \"-V\" || FAILED=1
+            test_tool sshd \"sshd\" \"-V\" || FAILED=1
             test_tool sudo \"sudo\" || FAILED=1
             test_tool nvim \"Neovim\" || FAILED=1
             test_tool starship \"Starship\" || FAILED=1
             test_tool atuin \"Atuin\" || FAILED=1
             test_tool mise \"Mise\" version || FAILED=1
             test_tool zellij \"Zellij\" || FAILED=1
+            test_tool jj \"Jujutsu\" || FAILED=1
+            test_tool rg \"RipGrep\" || FAILED=1
+            test_tool fzf \"fzf\" || FAILED=1
+
+            ss -lnt '( sport = :22 )' | grep -q LISTEN || {
+              FAILED=1
+              echo \"⚠ ssh check FAILED: Port 22 is not listened to.\"
+            }
 
             if [ \"$EXPECTED_ARCH\" == \"arm64\" ]; then
               if [ \"\$(uname -m)\" != \"aarch64\" ]; then
@@ -814,12 +824,23 @@ jobs:
             test_tool python "Python"; or set FAILED 1
             test_tool go "Go" version; or set FAILED 1
             test_tool wasm-opt "Binaryen"; or set FAILED 1
+            test_tool ssh "ssh" "-V"; or set FAILED 1
+            test_tool sshd "sshd" "-V"; or set FAILED 1
             test_tool sudo "sudo"; or set FAILED 1
             test_tool nvim "Neovim"; or set FAILED 1
             test_tool starship "Starship"; or set FAILED 1
             test_tool atuin "Atuin"; or set FAILED 1
             test_tool mise "Mise" version; or set FAILED 1
             test_tool zellij "Zellij"; or set FAILED 1
+            test_tool jj "Jujutsu"; or set FAILED 1
+            test_tool rg "RipGrep"; or set FAILED 1
+            test_tool fzf "fzf"; or set FAILED 1
+
+            ss -lnt '( sport = :22 )' | grep -q LISTEN
+              or begin
+                set -g FAILED 1
+                echo "⚠ ssh check FAILED: Port 22 is not listened to."
+              end
 
             echo ""
             if test $FAILED -eq 1
